<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

Students name in this Group:
- Gabriel Okazaki
- Julio Socher
- Kateryna Solonenko
- Mohit Sabharwal
- Riya Gupta
- Vaibhav Saini

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [21]:
a_mat = np.array([[5, 2, 3],[6,1,3],[2,4,1]])
print('A matrix:')
print(a_mat)

b_mat = a_mat[:2, 0:2]
print('B matrix:')
print(b_mat)

print('C matrix:')
print(a_mat[1:, 1:])

A matrix:
[[5 2 3]
 [6 1 3]
 [2 4 1]]
B matrix:
[[5 2]
 [6 1]]
C matrix:
[[1 3]
 [4 1]]


In [16]:
d_mat = np.array([[4, -7, 4], [5, 6, -1], [-4, 2, 5]])
print(d_mat)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [20]:
ad_mat = np.matmul(a_mat, d_mat)
print('AD matrix:')
print(ad_mat)

da_mat = np.matmul(d_mat, a_mat)
print('DA matrix:')
print(da_mat)

print('The matrices are different!')

AD matrix:
[[ 18 -17  33]
 [ 17 -30  38]
 [ 24  12   9]]
DA matrix:
[[-14  17  -5]
 [ 59  12  32]
 [  2  14  -1]]
The matrices are different!


In [24]:
print(f'Manual calculation of determinant of B: {5*1-2*6}')

man_inv = 1/(5*1-2*6)*np.array([[1,-2],[-6,5]])
print('Manual inverse B matrix:')
print(man_inv)

print(f'NumPy calculation of determinant of B: {det(b_mat)}')
print(f'Numpy inverse B matrix:')
print(inv(b_mat))

Manual calculation of determinant of B: -7
Manual inverse B matrix:
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]
NumPy calculation of determinant of B: -6.999999999999999
Numpy inverse B matrix:
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


In [27]:
print('Inverse of D:')
print(inv(d_mat))
print('DDinv matrix:')
print(np.matmul(d_mat, inv(d_mat)))
print('DinvD matrix:')
print(np.matmul(inv(d_mat), d_mat))

Inverse of D:
[[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]]
DDinv matrix:
[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 6.93889390e-17  1.00000000e+00 -5.55111512e-17]
 [-1.38777878e-17 -8.32667268e-17  1.00000000e+00]]
DinvD matrix:
[[ 1.00000000e+00  6.93889390e-17  6.93889390e-18]
 [ 2.77555756e-17  1.00000000e+00 -2.08166817e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
